"""customer tickets

Revision ID: f1e1485684fa
Revises: 01c0483772bc
Create Date: 2026-10-05 18:40:53.270906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base  # noqa: F401 - custom column types


# revision identifiers, used by Alembic.
revision: str = 'f1e1485684fa'
down_revision: Union[str, Sequence[str], None] = '01c0483772bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_categories',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subcategories', sa.JSON(), nullable=False),
    sa.Column('default_priority', sa.String(length=20), nullable=False),
    sa.Column('task_category', sa.String(length=40), nullable=False),
    sa.Column('preferred_vendor_type', sa.String(length=40), nullable=True),
    sa.Column('response_sla_minutes', sa.Integer(), nullable=True),
    sa.Column('resolution_sla_minutes', sa.Integer(), nullable=True),
    sa.Column('customer_sets_priority', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_index(op.f('ix_ticket_categories_tenant_id'), 'ticket_categories', ['tenant_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_deliveries_entity_id'), 'notification_deliveries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_notification_id'), 'notification_deliveries', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_status'), 'notification_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_tenant_id'), 'notification_deliveries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_user_id'), 'notification_deliveries', ['user_id'], unique=False)
    op.create_table('tickets',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('preferred_time', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('assigned_to_type', sa.String(length=10), nullable=True),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('maintenance_task_id', sa.Uuid(), nullable=True),
    sa.Column('resume_status', sa.String(length=30), nullable=True),
    sa.Column('due_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('verified_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('reopened_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reopen_count', sa.Integer(), nullable=False),
    sa.Column('rework_count', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('feedback_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('customer_confirmation', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'number')
    )
    op.create_index(op.f('ix_tickets_assigned_to_id'), 'tickets', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tickets_category_id'), 'tickets', ['category_id'], unique=False)
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tickets_due_at'), 'tickets', ['due_at'], unique=False)
    op.create_index(op.f('ix_tickets_number'), 'tickets', ['number'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_property_id'), 'tickets', ['property_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.create_table('ticket_assignments',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_type', sa.String(length=10), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_task_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('due_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('accepted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('unassigned_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('unassign_reason', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_assignments_assignee_id'), 'ticket_assignments', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_ticket_assignments_tenant_id'), 'ticket_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ticket_assignments_ticket_id'), 'ticket_assignments', ['ticket_id'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('comment_type', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comments_tenant_id'), 'ticket_comments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    op.create_table('ticket_evidence',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'media_id')
    )
    op.create_index(op.f('ix_ticket_evidence_media_id'), 'ticket_evidence', ['media_id'], unique=False)
    op.create_index(op.f('ix_ticket_evidence_tenant_id'), 'ticket_evidence', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ticket_evidence_ticket_id'), 'ticket_evidence', ['ticket_id'], unique=False)
    op.create_table('ticket_slas',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('response_due_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolution_due_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('first_response_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('response_breached', sa.Boolean(), nullable=False),
    sa.Column('resolution_breached', sa.Boolean(), nullable=False),
    sa.Column('at_risk_notified_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('breach_notified_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_index(op.f('ix_ticket_slas_resolution_due_at'), 'ticket_slas', ['resolution_due_at'], unique=False)
    op.create_index(op.f('ix_ticket_slas_response_due_at'), 'ticket_slas', ['response_due_at'], unique=False)
    op.create_index(op.f('ix_ticket_slas_tenant_id'), 'ticket_slas', ['tenant_id'], unique=False)
    op.create_table('ticket_status_history',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_history_tenant_id'), 'ticket_status_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ticket_status_history_ticket_id'), 'ticket_status_history', ['ticket_id'], unique=False)
    op.add_column('maintenance_tasks', sa.Column('ticket_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_maintenance_tasks_ticket_id'), 'maintenance_tasks', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_index(op.f('ix_maintenance_tasks_ticket_id'), table_name='maintenance_tasks')
    op.drop_column('maintenance_tasks', 'ticket_id')
    op.drop_index(op.f('ix_ticket_status_history_ticket_id'), table_name='ticket_status_history')
    op.drop_index(op.f('ix_ticket_status_history_tenant_id'), table_name='ticket_status_history')
    op.drop_table('ticket_status_history')
    op.drop_index(op.f('ix_ticket_slas_tenant_id'), table_name='ticket_slas')
    op.drop_index(op.f('ix_ticket_slas_response_due_at'), table_name='ticket_slas')
    op.drop_index(op.f('ix_ticket_slas_resolution_due_at'), table_name='ticket_slas')
    op.drop_table('ticket_slas')
    op.drop_index(op.f('ix_ticket_evidence_ticket_id'), table_name='ticket_evidence')
    op.drop_index(op.f('ix_ticket_evidence_tenant_id'), table_name='ticket_evidence')
    op.drop_index(op.f('ix_ticket_evidence_media_id'), table_name='ticket_evidence')
    op.drop_table('ticket_evidence')
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_tenant_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_ticket_assignments_ticket_id'), table_name='ticket_assignments')
    op.drop_index(op.f('ix_ticket_assignments_tenant_id'), table_name='ticket_assignments')
    op.drop_index(op.f('ix_ticket_assignments_assignee_id'), table_name='ticket_assignments')
    op.drop_table('ticket_assignments')
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_property_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_due_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_notification_deliveries_user_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_tenant_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_status'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_notification_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_entity_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_ticket_categories_tenant_id'), table_name='ticket_categories')
    op.drop_table('ticket_categories')
    # ### end Alembic commands ###
