"""account security

Revision ID: 8ee631a554bb
Revises: bd902cee9a57
Create Date: 2026-10-06 01:16:47.576439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base  # noqa: F401 - custom column types


# revision identifiers, used by Alembic.
revision: str = '8ee631a554bb'
down_revision: Union[str, Sequence[str], None] = 'bd902cee9a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('expires_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_destination'), 'otp_codes', ['destination'], unique=False)
    op.create_index(op.f('ix_otp_codes_purpose'), 'otp_codes', ['purpose'], unique=False)
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_table('signup_requests',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('plot_number', sa.String(length=40), nullable=True),
    sa.Column('relation', sa.String(length=30), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('service_categories', sa.JSON(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signup_requests_status'), 'signup_requests', ['status'], unique=False)
    op.create_index(op.f('ix_signup_requests_tenant_id'), 'signup_requests', ['tenant_id'], unique=False)
    op.add_column('refresh_tokens', sa.Column('ip', sa.String(length=64), nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_used_at', app.models.base.UTCDateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('phone_verified_at', app.models.base.UTCDateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', app.models.base.UTCDateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('totp_secret_enc', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('totp_enabled_at', app.models.base.UTCDateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('recovery_codes', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_codes')
    op.drop_column('users', 'totp_enabled_at')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret_enc')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    op.drop_column('users', 'phone_verified_at')
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'ip')
    op.drop_index(op.f('ix_signup_requests_tenant_id'), table_name='signup_requests')
    op.drop_index(op.f('ix_signup_requests_status'), table_name='signup_requests')
    op.drop_table('signup_requests')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_purpose'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_destination'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
