"""whatsapp channel

Revision ID: bd902cee9a57
Revises: f1e1485684fa
Create Date: 2026-10-05 20:59:42.342177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base  # noqa: F401 - custom column types


# revision identifiers, used by Alembic.
revision: str = 'bd902cee9a57'
down_revision: Union[str, Sequence[str], None] = 'f1e1485684fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_messages',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('wamid', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wamid')
    )
    op.create_index(op.f('ix_whatsapp_messages_phone'), 'whatsapp_messages', ['phone'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_tenant_id'), 'whatsapp_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_user_id'), 'whatsapp_messages', ['user_id'], unique=False)
    op.add_column('notification_deliveries', sa.Column('provider_message_id', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_notification_deliveries_provider_message_id'), 'notification_deliveries', ['provider_message_id'], unique=False)
    op.add_column('users', sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('whatsapp_opt_in_at', app.models.base.UTCDateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('whatsapp_last_inbound_at', app.models.base.UTCDateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'whatsapp_last_inbound_at')
    op.drop_column('users', 'whatsapp_opt_in_at')
    op.drop_column('users', 'whatsapp_opt_in')
    op.drop_index(op.f('ix_notification_deliveries_provider_message_id'), table_name='notification_deliveries')
    op.drop_column('notification_deliveries', 'provider_message_id')
    op.drop_index(op.f('ix_whatsapp_messages_user_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_tenant_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_phone'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    # ### end Alembic commands ###
