"""initial schema

Revision ID: e06963a28b27
Revises: 
Create Date: 2026-10-05 17:30:09.703633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base  # noqa: F401 - custom column types


# revision identifiers, used by Alembic.
revision: str = 'e06963a28b27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook_events',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('modules', sa.JSON(), nullable=False),
    sa.Column('max_properties', sa.Integer(), nullable=True),
    sa.Column('storage_quota_gb', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('billing_plans',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('basis', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frequency_months', sa.Integer(), nullable=False),
    sa.Column('due_days', sa.Integer(), nullable=False),
    sa.Column('late_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('custom_amounts', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_plans_tenant_id'), 'billing_plans', ['tenant_id'], unique=False)
    op.create_table('checklist_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_templates_category'), 'checklist_templates', ['category'], unique=False)
    op.create_index(op.f('ix_checklist_templates_tenant_id'), 'checklist_templates', ['tenant_id'], unique=False)
    op.create_table('counters',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'kind', 'year')
    )
    op.create_table('evidence_policies',
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('before_photo', sa.Boolean(), nullable=False),
    sa.Column('after_photo', sa.Boolean(), nullable=False),
    sa.Column('checklist', sa.Boolean(), nullable=False),
    sa.Column('gps', sa.Boolean(), nullable=False),
    sa.Column('video', sa.Boolean(), nullable=False),
    sa.Column('materials', sa.Boolean(), nullable=False),
    sa.Column('invoice', sa.Boolean(), nullable=False),
    sa.Column('qr_scan', sa.Boolean(), nullable=False),
    sa.Column('supervisor_approval', sa.Boolean(), nullable=False),
    sa.Column('resident_acknowledgement', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'category')
    )
    op.create_index(op.f('ix_evidence_policies_tenant_id'), 'evidence_policies', ['tenant_id'], unique=False)
    op.create_table('layouts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layouts_tenant_id'), 'layouts', ['tenant_id'], unique=False)
    op.create_table('patrol_routes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrol_routes_tenant_id'), 'patrol_routes', ['tenant_id'], unique=False)
    op.create_table('vendors',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('service_categories', sa.JSON(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('patrol_checkpoints',
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(length=120), nullable=False),
    sa.Column('nfc_id', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['patrol_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrol_checkpoints_qr_code'), 'patrol_checkpoints', ['qr_code'], unique=False)
    op.create_index(op.f('ix_patrol_checkpoints_route_id'), 'patrol_checkpoints', ['route_id'], unique=False)
    op.create_index(op.f('ix_patrol_checkpoints_tenant_id'), 'patrol_checkpoints', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('invite_token_hash', sa.String(length=128), nullable=True),
    sa.Column('invite_expires_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_invite_token_hash'), 'users', ['invite_token_hash'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('attendance',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_tenant_id'), 'attendance', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_index(op.f('ix_attendance_work_date'), 'attendance', ['work_date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('media',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('client_ref', sa.String(length=80), nullable=True),
    sa.Column('captured_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=400), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('expected_sha256', sa.String(length=64), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('replaces_id', sa.Uuid(), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['replaces_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key'),
    sa.UniqueConstraint('uploaded_by', 'client_ref')
    )
    op.create_index(op.f('ix_media_entity_id'), 'media', ['entity_id'], unique=False)
    op.create_index(op.f('ix_media_entity_type'), 'media', ['entity_type'], unique=False)
    op.create_index(op.f('ix_media_sha256'), 'media', ['sha256'], unique=False)
    op.create_index(op.f('ix_media_status'), 'media', ['status'], unique=False)
    op.create_index(op.f('ix_media_tenant_id'), 'media', ['tenant_id'], unique=False)
    op.create_table('notices',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('starts_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ends_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=False),
    sa.Column('published_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_tenant_id'), 'notices', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('delivery', sa.JSON(), nullable=False),
    sa.Column('read_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patrol_runs',
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('guard_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['patrol_routes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrol_runs_guard_id'), 'patrol_runs', ['guard_id'], unique=False)
    op.create_index(op.f('ix_patrol_runs_route_id'), 'patrol_runs', ['route_id'], unique=False)
    op.create_index(op.f('ix_patrol_runs_tenant_id'), 'patrol_runs', ['tenant_id'], unique=False)
    op.create_table('properties',
    sa.Column('layout_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('plot_number', sa.String(length=40), nullable=False),
    sa.Column('block', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_phone', sa.String(length=30), nullable=True),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_index(op.f('ix_properties_layout_id'), 'properties', ['layout_id'], unique=False)
    op.create_index(op.f('ix_properties_plot_number'), 'properties', ['plot_number'], unique=False)
    op.create_index(op.f('ix_properties_tenant_id'), 'properties', ['tenant_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('keys', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_tenant_id'), 'push_subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('device', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('staff_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('shift_name', sa.String(length=60), nullable=True),
    sa.Column('shift_start', sa.String(length=5), nullable=True),
    sa.Column('shift_end', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_profiles_tenant_id'), 'staff_profiles', ['tenant_id'], unique=False)
    op.create_table('sync_operations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_op_id', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('client_timestamp', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_op_id')
    )
    op.create_index(op.f('ix_sync_operations_tenant_id'), 'sync_operations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sync_operations_user_id'), 'sync_operations', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('qr_code', sa.String(length=120), nullable=False),
    sa.Column('nfc_id', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('layout_id', sa.Uuid(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('installed_on', sa.Date(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('service_interval_days', sa.Integer(), nullable=True),
    sa.Column('next_service_due', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code'),
    sa.UniqueConstraint('tenant_id', 'qr_code')
    )
    op.create_index(op.f('ix_assets_nfc_id'), 'assets', ['nfc_id'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('complaints',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_staff_id', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('maintenance_task_id', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'number')
    )
    op.create_index(op.f('ix_complaints_number'), 'complaints', ['number'], unique=False)
    op.create_index(op.f('ix_complaints_property_id'), 'complaints', ['property_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_tenant_id'), 'complaints', ['tenant_id'], unique=False)
    op.create_table('incidents',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('occurred_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('reported_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('sos_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'number')
    )
    op.create_index(op.f('ix_incidents_number'), 'incidents', ['number'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('inspections',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('inspector_id', sa.Uuid(), nullable=True),
    sa.Column('is_property_watch', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('overall_condition', sa.String(length=20), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'number')
    )
    op.create_index(op.f('ix_inspections_number'), 'inspections', ['number'], unique=False)
    op.create_index(op.f('ix_inspections_property_id'), 'inspections', ['property_id'], unique=False)
    op.create_index(op.f('ix_inspections_tenant_id'), 'inspections', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'property_id', 'period_start'),
    sa.UniqueConstraint('tenant_id', 'number')
    )
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=False)
    op.create_index(op.f('ix_invoices_property_id'), 'invoices', ['property_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('patrol_scans',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_id', sa.Uuid(), nullable=False),
    sa.Column('scanned_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('photo_media_id', sa.Uuid(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['patrol_checkpoints.id'], ),
    sa.ForeignKeyConstraint(['photo_media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['patrol_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrol_scans_run_id'), 'patrol_scans', ['run_id'], unique=False)
    op.create_index(op.f('ix_patrol_scans_tenant_id'), 'patrol_scans', ['tenant_id'], unique=False)
    op.create_table('residents',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('in_directory', sa.Boolean(), nullable=False),
    sa.Column('move_in', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residents_property_id'), 'residents', ['property_id'], unique=False)
    op.create_index(op.f('ix_residents_tenant_id'), 'residents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_residents_user_id'), 'residents', ['user_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('make_model', sa.String(length=100), nullable=True),
    sa.Column('photo_media_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photo_media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'number')
    )
    op.create_index(op.f('ix_vehicles_number'), 'vehicles', ['number'], unique=False)
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    op.create_table('visitors',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('host_name', sa.String(length=200), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('photo_media_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pre_approved', sa.Boolean(), nullable=False),
    sa.Column('expected_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('entry_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('exit_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('guard_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guard_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['photo_media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_property_id'), 'visitors', ['property_id'], unique=False)
    op.create_index(op.f('ix_visitors_status'), 'visitors', ['status'], unique=False)
    op.create_index(op.f('ix_visitors_tenant_id'), 'visitors', ['tenant_id'], unique=False)
    op.create_table('complaint_comments',
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_comments_complaint_id'), 'complaint_comments', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_comments_tenant_id'), 'complaint_comments', ['tenant_id'], unique=False)
    op.create_table('incident_updates',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status_change', sa.String(length=40), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_updates_incident_id'), 'incident_updates', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_updates_tenant_id'), 'incident_updates', ['tenant_id'], unique=False)
    op.create_table('maintenance_schedules',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('location_note', sa.String(length=300), nullable=True),
    sa.Column('checklist_template_id', sa.Uuid(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('due_after_hours', sa.Integer(), nullable=False),
    sa.Column('next_run_on', sa.Date(), nullable=False),
    sa.Column('assigned_staff_id', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_generated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['checklist_templates.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_schedules_tenant_id'), 'maintenance_schedules', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('provider_order_id', sa.String(length=100), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('receipt_number', sa.String(length=40), nullable=True),
    sa.Column('paid_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('reconciled_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_property_id'), 'payments', ['property_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_order_id'), 'payments', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('sos_alerts',
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_alerts_status'), 'sos_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_sos_alerts_tenant_id'), 'sos_alerts', ['tenant_id'], unique=False)
    op.create_table('vehicle_logs',
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('visitor_id', sa.Uuid(), nullable=True),
    sa.Column('is_visitor', sa.Boolean(), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('guard_id', sa.Uuid(), nullable=False),
    sa.Column('photo_media_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['photo_media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_logs_at'), 'vehicle_logs', ['at'], unique=False)
    op.create_index(op.f('ix_vehicle_logs_tenant_id'), 'vehicle_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_vehicle_logs_vehicle_number'), 'vehicle_logs', ['vehicle_number'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('layout_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('complaint_id', sa.Uuid(), nullable=True),
    sa.Column('inspection_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('location_note', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_staff_id', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('supervisor_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('due_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('approved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('overdue_notified_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('start_latitude', sa.Float(), nullable=True),
    sa.Column('start_longitude', sa.Float(), nullable=True),
    sa.Column('complete_latitude', sa.Float(), nullable=True),
    sa.Column('complete_longitude', sa.Float(), nullable=True),
    sa.Column('gps_accuracy_m', sa.Float(), nullable=True),
    sa.Column('asset_scanned_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('asset_scan_method', sa.String(length=10), nullable=True),
    sa.Column('work_notes', sa.Text(), nullable=True),
    sa.Column('issue_found', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('review_decision', sa.String(length=20), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('rework_count', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resident_ack_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resident_ack_by', sa.Uuid(), nullable=True),
    sa.Column('resident_ack_note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['resident_ack_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['maintenance_schedules.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'number')
    )
    op.create_index(op.f('ix_maintenance_tasks_asset_id'), 'maintenance_tasks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_assigned_staff_id'), 'maintenance_tasks', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_category'), 'maintenance_tasks', ['category'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_due_at'), 'maintenance_tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_number'), 'maintenance_tasks', ['number'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_property_id'), 'maintenance_tasks', ['property_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_status'), 'maintenance_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_tenant_id'), 'maintenance_tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_vendor_id'), 'maintenance_tasks', ['vendor_id'], unique=False)
    op.create_table('evidence_exceptions',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('requirement', sa.String(length=30), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_exceptions_task_id'), 'evidence_exceptions', ['task_id'], unique=False)
    op.create_index(op.f('ix_evidence_exceptions_tenant_id'), 'evidence_exceptions', ['tenant_id'], unique=False)
    op.create_table('expenses',
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('maintenance_task_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_tenant_id'), 'expenses', ['tenant_id'], unique=False)
    op.create_table('inspection_items',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('point', sa.String(length=40), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_task_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follow_up_task_id'], ['maintenance_tasks.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_items_inspection_id'), 'inspection_items', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_inspection_items_tenant_id'), 'inspection_items', ['tenant_id'], unique=False)
    op.create_table('maintenance_checklist_items',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('checked_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_checklist_items_task_id'), 'maintenance_checklist_items', ['task_id'], unique=False)
    op.create_index(op.f('ix_maintenance_checklist_items_tenant_id'), 'maintenance_checklist_items', ['tenant_id'], unique=False)
    op.create_table('maintenance_comments',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_comments_task_id'), 'maintenance_comments', ['task_id'], unique=False)
    op.create_index(op.f('ix_maintenance_comments_tenant_id'), 'maintenance_comments', ['tenant_id'], unique=False)
    op.create_table('maintenance_evidence',
    sa.Column('maintenance_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('captured_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rework_round', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_evidence_evidence_type'), 'maintenance_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_maintenance_evidence_maintenance_id'), 'maintenance_evidence', ['maintenance_id'], unique=False)
    op.create_index(op.f('ix_maintenance_evidence_media_id'), 'maintenance_evidence', ['media_id'], unique=False)
    op.create_index(op.f('ix_maintenance_evidence_tenant_id'), 'maintenance_evidence', ['tenant_id'], unique=False)
    op.create_table('maintenance_materials',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_materials_task_id'), 'maintenance_materials', ['task_id'], unique=False)
    op.create_index(op.f('ix_maintenance_materials_tenant_id'), 'maintenance_materials', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_materials_tenant_id'), table_name='maintenance_materials')
    op.drop_index(op.f('ix_maintenance_materials_task_id'), table_name='maintenance_materials')
    op.drop_table('maintenance_materials')
    op.drop_index(op.f('ix_maintenance_evidence_tenant_id'), table_name='maintenance_evidence')
    op.drop_index(op.f('ix_maintenance_evidence_media_id'), table_name='maintenance_evidence')
    op.drop_index(op.f('ix_maintenance_evidence_maintenance_id'), table_name='maintenance_evidence')
    op.drop_index(op.f('ix_maintenance_evidence_evidence_type'), table_name='maintenance_evidence')
    op.drop_table('maintenance_evidence')
    op.drop_index(op.f('ix_maintenance_comments_tenant_id'), table_name='maintenance_comments')
    op.drop_index(op.f('ix_maintenance_comments_task_id'), table_name='maintenance_comments')
    op.drop_table('maintenance_comments')
    op.drop_index(op.f('ix_maintenance_checklist_items_tenant_id'), table_name='maintenance_checklist_items')
    op.drop_index(op.f('ix_maintenance_checklist_items_task_id'), table_name='maintenance_checklist_items')
    op.drop_table('maintenance_checklist_items')
    op.drop_index(op.f('ix_inspection_items_tenant_id'), table_name='inspection_items')
    op.drop_index(op.f('ix_inspection_items_inspection_id'), table_name='inspection_items')
    op.drop_table('inspection_items')
    op.drop_index(op.f('ix_expenses_tenant_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_evidence_exceptions_tenant_id'), table_name='evidence_exceptions')
    op.drop_index(op.f('ix_evidence_exceptions_task_id'), table_name='evidence_exceptions')
    op.drop_table('evidence_exceptions')
    op.drop_index(op.f('ix_maintenance_tasks_vendor_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_tenant_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_status'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_property_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_number'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_due_at'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_category'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_assigned_staff_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_asset_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_vehicle_logs_vehicle_number'), table_name='vehicle_logs')
    op.drop_index(op.f('ix_vehicle_logs_tenant_id'), table_name='vehicle_logs')
    op.drop_index(op.f('ix_vehicle_logs_at'), table_name='vehicle_logs')
    op.drop_table('vehicle_logs')
    op.drop_index(op.f('ix_sos_alerts_tenant_id'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_status'), table_name='sos_alerts')
    op.drop_table('sos_alerts')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_property_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_maintenance_schedules_tenant_id'), table_name='maintenance_schedules')
    op.drop_table('maintenance_schedules')
    op.drop_index(op.f('ix_incident_updates_tenant_id'), table_name='incident_updates')
    op.drop_index(op.f('ix_incident_updates_incident_id'), table_name='incident_updates')
    op.drop_table('incident_updates')
    op.drop_index(op.f('ix_complaint_comments_tenant_id'), table_name='complaint_comments')
    op.drop_index(op.f('ix_complaint_comments_complaint_id'), table_name='complaint_comments')
    op.drop_table('complaint_comments')
    op.drop_index(op.f('ix_visitors_tenant_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_status'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_property_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_residents_user_id'), table_name='residents')
    op.drop_index(op.f('ix_residents_tenant_id'), table_name='residents')
    op.drop_index(op.f('ix_residents_property_id'), table_name='residents')
    op.drop_table('residents')
    op.drop_index(op.f('ix_patrol_scans_tenant_id'), table_name='patrol_scans')
    op.drop_index(op.f('ix_patrol_scans_run_id'), table_name='patrol_scans')
    op.drop_table('patrol_scans')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_property_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inspections_tenant_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_property_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_number'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_number'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_complaints_tenant_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_property_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_number'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_nfc_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_sync_operations_user_id'), table_name='sync_operations')
    op.drop_index(op.f('ix_sync_operations_tenant_id'), table_name='sync_operations')
    op.drop_table('sync_operations')
    op.drop_index(op.f('ix_staff_profiles_tenant_id'), table_name='staff_profiles')
    op.drop_table('staff_profiles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_tenant_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_properties_tenant_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_plot_number'), table_name='properties')
    op.drop_index(op.f('ix_properties_layout_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_patrol_runs_tenant_id'), table_name='patrol_runs')
    op.drop_index(op.f('ix_patrol_runs_route_id'), table_name='patrol_runs')
    op.drop_index(op.f('ix_patrol_runs_guard_id'), table_name='patrol_runs')
    op.drop_table('patrol_runs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notices_tenant_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_media_tenant_id'), table_name='media')
    op.drop_index(op.f('ix_media_status'), table_name='media')
    op.drop_index(op.f('ix_media_sha256'), table_name='media')
    op.drop_index(op.f('ix_media_entity_type'), table_name='media')
    op.drop_index(op.f('ix_media_entity_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendance_work_date'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_user_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_tenant_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_invite_token_hash'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patrol_checkpoints_tenant_id'), table_name='patrol_checkpoints')
    op.drop_index(op.f('ix_patrol_checkpoints_route_id'), table_name='patrol_checkpoints')
    op.drop_index(op.f('ix_patrol_checkpoints_qr_code'), table_name='patrol_checkpoints')
    op.drop_table('patrol_checkpoints')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_patrol_routes_tenant_id'), table_name='patrol_routes')
    op.drop_table('patrol_routes')
    op.drop_index(op.f('ix_layouts_tenant_id'), table_name='layouts')
    op.drop_table('layouts')
    op.drop_index(op.f('ix_evidence_policies_tenant_id'), table_name='evidence_policies')
    op.drop_table('evidence_policies')
    op.drop_table('counters')
    op.drop_index(op.f('ix_checklist_templates_tenant_id'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_category'), table_name='checklist_templates')
    op.drop_table('checklist_templates')
    op.drop_index(op.f('ix_billing_plans_tenant_id'), table_name='billing_plans')
    op.drop_table('billing_plans')
    op.drop_table('tenants')
    op.drop_table('payment_webhook_events')
    # ### end Alembic commands ###
